### ISSUE TITLE
NullPointerException in namestoagehistory

### ISSUE THREAD

**Issue by xloem** [Qoracoin/Qora#34]
See http://qora.co.in:9090/index/namestoragehistory.html?name=demo_name which throws an exception.

I'm using this patch locally:
```
diff --git a/Qora/src/qora/web/WebNameStorageHistoryHelper.java b/Qora/src/qora/web/WebNameStorageHistoryHelper.java
index f35bd5c..d37fef7 100644
--- a/Qora/src/qora/web/WebNameStorageHistoryHelper.java
+++ b/Qora/src/qora/web/WebNameStorageHistoryHelper.java
@@ -72,6 +72,9 @@ public class WebNameStorageHistoryHelper {
 
                Map<String, String> map = orphanNameStorageMap.get(tx.getSignature());
 
+               if (map == null)
+                       return result;
+
                Set<String> orphanKeySet = map.keySet();
 
                // initializing tempnamestorage with old values

```
But it leaves broken items on the interface.

**Comment by catbref** [comment]
```
2017-12-01 13:28:29 ERROR WebResource:390 - 
java.lang.NullPointerException
	at qora.web.WebNameStorageHistoryHelper.getKeyHistory(WebNameStorageHistoryHelper.java:75)
	at qora.web.WebNameStorageHistoryHelper.getHistory(WebNameStorageHistoryHelper.java:44)
	at webserver.WebResource.getNameStorage(WebResource.java:381)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by catbref** [comment]
```
Transaction: zVfAvH9kHBpk7nBUkP8sEySA7G3aJt4cMtBvTbz8CQ5rQukvw76UuKkKFGp6wYA4nXq4Ayq1r2Mv2bgjMoNjjx5
Height: 166429
ArbitraryTransactionV1, service 10 (NameStorage)
Payload: "{"name":"demo_name"}"
```

This transaction has no name storage key like "addcomplete" so assuming it didn't make it into the orphan map and hence when looked up by transaction signature in WebNameStorageHistoryHelper.java:73:

`Map<String, String> map = orphanNameStorageMap.get(tx.getSignature());`

map is then assigned null which causes NPE at the next line (75):

`Set<String> orphanKeySet = map.keySet();`

So OP's patch looks like to be on the right track but more investigation into subsequent "broken items on the interface" needed.

**Comment by fuzzyTew** [comment]
It’s so incredible to see some renewed energy on this project!
