### ISSUE TITLE
NPE [when block doesn't arrive from connected peer]

### ISSUE THREAD

**Issue by sytolk** [Qoracoin/Qora#61]
Process Block 17253
2016-10-14 19:30:34 ERROR Controller:1027 - 
java.lang.NullPointerException
    at qora.Synchronizer.process(Synchronizer.java:339)
    at qora.Synchronizer.synchronize(Synchronizer.java:195)
    at controller.Controller.update(Controller.java:1024)
    at qora.BlockGenerator.run(BlockGenerator.java:178)
2016-10-14 19:30:34 WARN  Network:117 - Connection error : /188.166.16.64 : null
2016-10-14 19:30:34 INFO  Network:91 - Connection close : /188.166.16.64
2016-10-14 19:31:55 INFO  Peer:146 - Failed to connect to : /2.84.51.78
2016-10-14 19:31:55 INFO  ConnectionCreator:118 - Connecting to peer 2.87.113.22 proposed by 188.166.16.64 :: 3 / 20 / 20 :: Connections: 0

**Comment by catbref** [comment]
Closed as fixed thanks to commit 9760b75
