### ISSUE TITLE
Wallet sync / DBMap ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by catbref** [Qoracoin/Qora#65]
```
2017-11-30 10:20:35 INFO  Wallet:474 - Synchronize wallet: 412000
2017-11-30 10:20:35 INFO  Wallet:917 - Wallet not synchronized with current blockchain: synchronizing wallet.
2017-11-30 10:20:35 INFO  Wallet:498 - Resetted balances
2017-11-30 10:20:35 INFO  Block:782 - Processed block 413120
2017-11-30 10:20:35 INFO  Block:782 - Processed block 413121
2017-11-30 10:20:35 ERROR DBMap:182 - 199452659
java.lang.ArrayIndexOutOfBoundsException: 199452659
        at org.mapdb.Volume$ByteBufferVol.getByte(Volume.java:429)
        at org.mapdb.Volume.getUnsignedShort(Volume.java:109)
        at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1046)
        at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:913)
        at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1098)
        at org.mapdb.StoreDirect.physAllocate(StoreDirect.java:666)
        at org.mapdb.StoreWAL.update(StoreWAL.java:404)
        at org.mapdb.Caches$HashTable.update(Caches.java:270)
        at org.mapdb.BTreeMap.put2(BTreeMap.java:746)
        at org.mapdb.BTreeMap.put(BTreeMap.java:643)
        at database.DBMap.set(DBMap.java:141)
        at database.HeightMap.set(HeightMap.java:87)
        at qora.block.Block.process(Block.java:755)
        at qora.block.Block.process(Block.java:710)
        at qora.Synchronizer.process(Synchronizer.java:353)
        at qora.Synchronizer.synchronize(Synchronizer.java:205)
        at controller.Controller.update(Controller.java:1034)
        at qora.BlockGenerator.run(BlockGenerator.java:184)
2017-11-30 10:20:35 ERROR DBMap:182 - 199452659
java.lang.ArrayIndexOutOfBoundsException: 199452659
        at org.mapdb.Volume$ByteBufferVol.getByte(Volume.java:429)
        at org.mapdb.Volume.getUnsignedShort(Volume.java:109)
        at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1046)
        at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:913)
        at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1109)
        at org.mapdb.StoreDirect.physAllocate(StoreDirect.java:666)
        at org.mapdb.StoreWAL.update(StoreWAL.java:404)
        at org.mapdb.Caches$HashTable.update(Caches.java:270)
        at org.mapdb.BTreeMap.put2(BTreeMap.java:746)
        at org.mapdb.BTreeMap.put(BTreeMap.java:643)
        at database.DBMap.set(DBMap.java:141)
        at database.BlockMap.add(BlockMap.java:172)
        at qora.block.Block.process(Block.java:777)
        at qora.block.Block.process(Block.java:710)
        at qora.Synchronizer.process(Synchronizer.java:353)
        at qora.Synchronizer.synchronize(Synchronizer.java:205)
        at controller.Controller.update(Controller.java:1034)
        at qora.BlockGenerator.run(BlockGenerator.java:184)
2017-11-30 10:20:35 INFO  Block:782 - Processed block 413122
2017-11-30 10:20:35 INFO  Wallet:917 - Wallet not synchronized with current blockchain: synchronizing wallet.
2017-11-30 10:20:35 INFO  Wallet:453 - Resetted maps
2017-11-30 10:20:35 INFO  Wallet:474 - Synchronize wallet: 2000
2017-11-30 10:20:35 INFO  Wallet:474 - Synchronize wallet: 4000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 6000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 8000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 10000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 12000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 14000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 16000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 18000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 20000
2017-11-30 10:20:36 INFO  Wallet:474 - Synchronize wallet: 22000
2017-11-30 10:20:37 INFO  Wallet:474 - Synchronize wallet: 24000
```

**Comment by smartspender** [comment]
hello, im on version 0.26.10 and my wallet isnt syncing bast block height 140751. Im trying to access qora that I sent to my wallet a long time ago. Before Poloniex delisted it. Can I please have some help?

**Comment by catbref** [comment]
I've reinstalled v0.26.10 and trying to resync the blockchain, However this ticket isn't the ideal place for this kind of support - please join our Discord channel at: https://discord.gg/bkE3XV
