### ISSUE TITLE
NullPointerException during NameStorageMap.remove()

### ISSUE THREAD

**Issue by catbref** [Qoracoin/Qora#66]
```
2017-11-11 04:13:27 ERROR DBMap:182 - 
java.lang.NullPointerException
	at org.mapdb.BTreeMap.put(BTreeMap.java:642)
	at database.DBMap.set(DBMap.java:141)
	at qora.web.NameStorageMap.remove(NameStorageMap.java:126)
	at utils.StorageUtils.addTxChangesToStorage(StorageUtils.java:191)
	at utils.StorageUtils.processUpdate(StorageUtils.java:147)
	at qora.transaction.ArbitraryTransaction.process(ArbitraryTransaction.java:224)
	at qora.block.Block.isValid(Block.java:695)
	at qora.block.Block.isValid(Block.java:571)
	at qora.Synchronizer.process(Synchronizer.java:349)
	at qora.Synchronizer.synchronize(Synchronizer.java:205)
	at controller.Controller.update(Controller.java:1034)
	at qora.BlockGenerator.run(BlockGenerator.java:184)
```

**Comment by catbref** [comment]
If this is caused by a specific transaction then it's before block 351116.
Also an ArbitraryTransaction with service=10 (i.e. name storage) and "removecomplete" key.

Also note that mapdb will throw NPE at BTreeMap.java:642 if either `key` or `value` is null.

Suspect code starts at NameStorageMap.java:121:
```
	public void remove(String name, String key) {
		Map<String, String> keyValueMap = this.get(name);
		if (keyValueMap != null) {
			keyValueMap.remove(key);
		}
		this.set(name, keyValueMap);
	}
```

This looks wrong because if `this.get(name)` returns null, i.e. `name` is not found in name storage map, then `this.set(name, keyValueMap)` is called with `keyValueMap` being null, and hence NPE thrown.

Surely if `name` is not found in the map then there's nothing to remove?

Which would change `remove()` to this:
```
	public void remove(String name, String key) {
		Map<String, String> keyValueMap = this.get(name);

		if (keyValueMap == null)
			return;

		keyValueMap.remove(key);
		this.set(name, keyValueMap);
	}
```
However, why would this trigger on _some_ resyncs from block 0 and not others?

Probably best action at this point is to add detection code to discover triggering transactions but keep current exception behaviour until cause is found.

**Comment by catbref** [comment]
```
Transaction: 2hcSQSAYvMkExD4i7WMX47yvhMAQCkscEkQXiM2rq1YyK23LYWAAhghGBF4fmVhBdpjqaKT59DDeauEwJBRF4qgT
Height: 303065
Creator: QMYPraQ49KMCy2qPM2yNSxVjgGeLrw8VC7
ArbitraryTransaction, service 10 (Name Storage)
Base58: 8L6yTJZH9X4XkDo6ywCKWs1ftM7mBQEh3JyZRtq1Rwdx8MwkgEFnHJwAkFDDURFBeXJhj4
WhdZT8MgJGb72AY
Payload: {"name":"qorawebwallet","removecomplete":"{\"website\":\"\"}"}
```

Interestingly, this is the first transaction after the name registration so this might explain why there's no existing record in the name storage map.

**Comment by catbref** [comment]
Fixed + tested
