### ISSUE TITLE
connection error causes unnecessary noise in logs?

### ISSUE THREAD

**Issue by catbref** [Qoracoin/Qora#67]
```
2017-11-11 04:35:58 WARN  Network:117 - Connection error : /216.126.198.27 : Socket closed
2017-11-11 04:35:58 ERROR Controller:1037 - Block buffer error
java.lang.Exception: Block buffer error
	at qora.BlockBuffer.getBlock(BlockBuffer.java:111)
	at qora.Synchronizer.synchronize(Synchronizer.java:192)
	at controller.Controller.update(Controller.java:1034)
	at qora.BlockGenerator.run(BlockGenerator.java:184)
2017-11-11 04:35:58 WARN  Network:117 - Connection error : /216.126.198.27 : Block buffer error
2017-11-11 04:35:58 WARN  Network:117 - Connection error : /216.126.198.27 : Socket closed
```

**Comment by catbref** [comment]
Less noise in v0.26.9
