### ISSUE TITLE
JSON issue when repopulating name storage during startup

### ISSUE THREAD

**Issue by catbref** [Qoracoin/Qora#74]
On a second start, the program would not visibly run (it would run in a background for a few minutes (and be seen in a program manager) and would dissapear completely after that)

```
The log file: "STARTUP ERROR: org.json.simple.JSONObject cannot be cast to java.lang.String
... ERROR Start:37 - log4j.properties not found, search path is C:\Program Files\Qora\log4j.properties using default!"
Starting Qora / version: 0.26.2.1 / build date: 2017-11-06 / ...
...INFO  NTP:30 - Adjusting time with 860 milliseconds.
...ERROR Start:114 - org.json.simple.JSONObject cannot be cast to java.lang.String
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to java.lang.String
   at utils.StorageUtils.getKeys(StorageUtils.java:288)
   at utils.StorageUtils.getAllKeysForOrphanSaving(StorageUtils.java:276)
   at utils.StorageUtils.processUpdate(StorageUtils.java:136)
   at utils.UpdateUtil.repopulateNameStorage(UpdateUtil.java:42)
   at controller.Controller.start(Controller.java:342)
   at Start.main(Start.java:99)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   at java.lang.reflect.Method.invoke(Unknown Source)
   at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)"
```

**Comment by catbref** [comment]
Still occasionally happens even after upgrade from v0.26.2.1 to v0.26.3.
Looking for a copy of broken database to find out why.

**Comment by catbref** [comment]
fixed with commit referenced above
