### ISSUE TITLE
Database/name service error

### ISSUE THREAD

**Issue by Rammelkast** [Qoracoin/Qora#88]
I started QORA and got the following error:

> 2018-02-25 19:01:03 WARN  StorageUtils:223 - Invalid name storage patch for name "2ndtest"
difflib.PatchFailedException: Incorrect Chunk: the chunk content doesn't match the target
        at difflib.Chunk.verify(Chunk.java:79) ~[Qora.jar:?]
        at difflib.ChangeDelta.verify(ChangeDelta.java:78) ~[Qora.jar:?]
        at difflib.ChangeDelta.applyTo(ChangeDelta.java:44) ~[Qora.jar:?]
        at difflib.Patch.applyTo(Patch.java:42) ~[Qora.jar:?]
        at utils.DiffHelper.patch(DiffHelper.java:49) ~[Qora.jar:?]
        at utils.StorageUtils.addTxChangesToStorage(StorageUtils.java:221) [Qora.jar:?]
        at utils.StorageUtils.processUpdate(StorageUtils.java:150) [Qora.jar:?]
        at utils.UpdateUtil.repopulateNameStorage(UpdateUtil.java:42) [Qora.jar:?]
        at controller.Controller.start(Controller.java:353) [Qora.jar:?]
        at Start.main(Start.java:75) [Qora.jar:?]

Now QORA keeps crashing, nothing works anymore.

**Comment by catbref** [comment]
If you see this message in the logs then the patch won't have applied to the name storage data belonging to (in this case) "2ndtest". (Upcoming commit removes the stack trace as it's not a code error but an error in the data submitted by the Qora user).

Patch failures shouldn't stop any other part of the Qora client from working though.
If your client has **other** issues then please do report back.

**Comment by catbref** [comment]
Here's are the 16 transactions, with patch failure messages, baked into the historic blockchain (so far):

```
Transaction Signature: 2kDKSxmRUKyktk5qupNZSYzs3SVBTJ5tjUZ4Cd5153dJQ7DV7tQQ8cfPnq4TtddgA5hGgYk78sBTKFt3zjMgrayS
Invalid name storage patch for name "2ndtest" and key "test": Incorrect Chunk: the chunk content doesn't match the target

Transaction Signature: yW2SAUNdhpv33j8b2AnmJgcSDv8kfceboyLJmyfGjza9DGvE8g8X6qE8rA8ZqQKzH6r2WpmabEdhN1sMNqMxTrq
Invalid name storage patch for name "smalladventure" and key "HEAD": Incorrect Chunk: the chunk content doesn't match the target

Transaction Signature: sq7DFptvS56PbEWR8oJddLEDRPMmU62AFeh4SpoBYDMMXTJnTYVhEV9WyfgoXmTxqSXWRa4mZ34ZA5aLqoLoGi1
Invalid name storage patch for name "smalladventure" and key "FOOT": Incorrect Chunk: the chunk content doesn't match the target

Transaction Signature: 8HPcYqD3U6xkrMEJzewhfQ9u6VVi86vM5G6mLXhdYAquE1vx7eVpLKUh7Ju7RPCJK5hUcqzgYxaoU1HLfRTTTy5
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the chunk content doesn't match the target

Transaction Signature: 5DbJVebCm7KNeRaXRf7rSKEFuRvtUg665u16C19WD3xMGyaEkmypWcRWEtfy3bB3kjwp526GyZJyhoJs1NEAVNb9
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the chunk content doesn't match the target

Transaction Signature: 4fkU4Tok6VFbQxZ4Q1TYQichYzKYaWofFjz1oAAyt3mQ1pQQsEJwMVe8YtEheY7L2QzcaJUYJGTvWCAe4j5eqKd8
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 3qkLwZic39E2PF4NeenAuriRtdcfok7BS3X19372Gw7MLYbNwfupWVpYWzL9H5e6xbX5GVkzuyQ3PzinDXsw81DP
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 2LfYCtBTC4asde3D2oFX1Knvw8t66WYvRkEkKopc2Kqm1KvA9Mu4wcaHkXi9cXr9NSSUgrrcBEM7C71noFi9VGT8
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 2kR1K6ESAw61gp4Y2oNneVKAEHtFgru7MWtBkZqt3R9pWmVoqxPumSrF2bQ1qkCqebteqnvbTic7er7EX3UtotAG
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 2t3jepCKn4NH4E342bdEZjFaY5iYFrRtgM3qq7fGABQ3obDZbKUAiRxepvtYG4ke5zRWAfPnfSUNxxvV9LKjsAZR
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 53HguCujeNunzN4jaQRAidXQBA4oYYPQPNjNZXC3D1PEokN15LpyzG87nqM3WNRQfjf5MoFARdbsVEMgxSxy1NZq
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 3hgFAnChNZaJ7j7EvJV3u2KDwYMSxTethtoZf3MW9SkVSXYoZrwGbvD5n2EEjubnpBqgAU448SKPDuqnqqbCzmJY
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 3wBsSEXe5TmxmXhDTCtptrXC5EvoXp9SbNp9L99T3YYN1h4JkqDbA2WWXjfS5WxV8igaahnWa2s9wkx2n6P6TbsD
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 3CLtLF2hTCp54qXnfAVkRZw867nAzz4i5XAGDexbHUWPJEMSueCa8uLQyJ7L8LUptgyWFsL5kB2TgLUniJRCWFAH
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 2xbEBNQLWN4Bd8mn6hdDYvHK3tT2Kq3jLfsYyecrhFYTi4ACcGLXpkUrBwXz4zDqcztAjhQi61oakzqYBdXm3GhE
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size

Transaction Signature: 3T1wKBe3RCeMgRx4iKFUGpEhLSLPspo5SFoAH9x6fUEvTXgVgNxga7kEvQY3bU6S2PSHBjRm63c9WPKLxobL3ecn
Invalid name storage patch for name "mytools" and key "qora.js": Incorrect Chunk: the position of chunk > target size
```

**Comment by catbref** [comment]
Please upgrade to the new v0.26.6 and report back if you still have issues.
In the meantime I'm closing this.
